name: 'Rust Codecov'
description: 'Instrument, test, collect coverage, and format it for codecov'
branding:
  icon: 'file-text'
  color: 'yellow'
inputs:
  output-path:
    description: 'the destination file path'
    required: false
    default: 'codecov.json'
  ignore-pattern:
    description: 'pattern to exclude from coverage'
    retuired: false
    default: '(.*\.cargo/registry/.*)|(.*\.rustup/.*)|($IGNORE_PATTERN)|(.*test.*)'
runs:
  using: 'composite'
  steps:
  - name: install nightly
    run: |
      rustup set profile minimal
      rustup toolchain install nightly
    shell: bash

  - name: Install llvm tools
    run: rustup install llvm-tools-preview
    shell: bash

  - name: Install cargo utilities
    run: cargo +nightly install cargo-binutils cargo-llvm-codecov-converter
    shell: bash

  - name: build test and cover
    run: |
      export OUTPUT_PATH=${{ inputs.output-path }}
      export IGNORE_PATTERN=${{ inputs.ignore-pattern }}
      ${{ github.action_path }}/build-test-cover.sh
    shell: bash
